/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.table.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TableUiModule extends AbstractTableUiModule {

	public TableUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
