/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.words.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import drkstr.hello.xtext.words.words.Paragraph;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class WordsLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public WordsLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	// --------------------------------------
	// Paragraph
	// --------------------------------------
	
	String text(Paragraph ele) {
		return "Paragraph";
	}

	String image(Paragraph ele) {
		return "paragraph.png";
	}
}
