/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import drkstr.hello.xtext.natural.core.ui.syntaxcoloring.NaturalHighlightingConfiguration;
import drkstr.hello.xtext.natural.core.ui.syntaxcoloring.NaturalSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NaturalUiModule extends AbstractNaturalUiModule {

	public NaturalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return NaturalHighlightingConfiguration.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return NaturalSemanticHighlightingCalculator.class;
	}
}
