/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NaturalRuntimeModule extends AbstractNaturalRuntimeModule {

}
