grammar drkstr.hello.xtext.table.Table with drkstr.hello.xtext.words.Words

import "http://www.hello.drkstr/xtext/words/Words"
generate table "http://www.hello.drkstr/xtext/table/Table"

TableModel:
	narrative=Narrative?
	Table=Table?
;

Narrative:
	(WordLiteral WordLiteral* EOL)+
;

Table:
	rows+=TableRow+
;

TableRow: {TableRow}
	'|' cols+=TableCol
	EOL
;

TableCol: {TableCol}
	TABLE_CELL
;

terminal TABLE_CELL: !('|' | '\n' | '\r')* '|';
