/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import drkstr.hello.xtext.natural.NaturalRuntimeModule;
import drkstr.hello.xtext.natural.NaturalStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NaturalIdeSetup extends NaturalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NaturalRuntimeModule(), new NaturalIdeModule()));
	}
	
}
