/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.serializer;

import drkstr.hello.xtext.natural.serializer.AbstractNaturalSemanticSequencer;

public class NaturalSemanticSequencer extends AbstractNaturalSemanticSequencer {
}
