/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.serializer;

import drkstr.hello.xtext.natural.serializer.AbstractNaturalSyntacticSequencer;

public class NaturalSyntacticSequencer extends AbstractNaturalSyntacticSequencer {
}
