/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.ui.contentassist;

import drkstr.hello.xtext.natural.core.ui.contentassist.AbstractNaturalProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class NaturalProposalProvider extends AbstractNaturalProposalProvider {
}
