/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.words.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class WordsWebModule extends AbstractWordsWebModule {
}
