/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.words.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import drkstr.hello.xtext.words.WordsRuntimeModule;
import drkstr.hello.xtext.words.WordsStandaloneSetup;
import drkstr.hello.xtext.words.ide.WordsIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class WordsWebSetup extends WordsStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WordsRuntimeModule(), new WordsIdeModule(), new WordsWebModule()));
	}
	
}
