/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.validation;

import static drkstr.hello.xtext.natural.core.natural.NaturalPackage.Literals.SCENARIO__STEPS;
import static drkstr.hello.xtext.natural.core.natural.NaturalPackage.Literals.SCENARIO__TITLE;
import static drkstr.hello.xtext.natural.core.validation.IssueCodes.MISSING_SCENARIO_STEPS;
import static drkstr.hello.xtext.natural.core.validation.IssueCodes.MISSING_SCENARIO_TITLE;

import org.eclipse.xtext.validation.Check;

import drkstr.hello.xtext.natural.core.natural.Scenario;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class NaturalValidator extends AbstractNaturalValidator {

	@Check
	public void missingScenarioSteps(Scenario model) {
		if (model.getSteps().isEmpty()) {
			String title = (model.getTitle() == null) ? "" : model.getTitle().trim();
			error(MISSING_SCENARIO_STEPS.message(title), model, SCENARIO__STEPS, MISSING_SCENARIO_STEPS.id());
		}
	}

	@Check
	public void missingScenarioTitle(Scenario model) {
		if (model.getTitle() == null || model.getTitle().trim() == "") {
			warning(MISSING_SCENARIO_TITLE.message(), model, SCENARIO__TITLE, MISSING_SCENARIO_TITLE.id());
		}
	}
}
