/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NaturalUiModule extends AbstractNaturalUiModule {

	public NaturalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
