/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.words;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WordsStandaloneSetup extends WordsStandaloneSetupGenerated {

	public static void doSetup() {
		new WordsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
