/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.natural.core.ide;

import drkstr.hello.xtext.natural.core.ide.AbstractNaturalIdeModule;

/**
 * Use this class to register ide components.
 */
public class NaturalIdeModule extends AbstractNaturalIdeModule {
}
