/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.table.tests

import com.google.inject.Inject
import drkstr.hello.xtext.table.table.Table
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TableInjectorProvider)
class TableParsingTest {
	@Inject
	ParseHelper<Table> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			| Hello, Tables! |
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
