/*
 * generated by Xtext 2.21.0
 */
package drkstr.hello.xtext.table.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import drkstr.hello.xtext.table.TableRuntimeModule;
import drkstr.hello.xtext.table.TableStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TableIdeSetup extends TableStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TableRuntimeModule(), new TableIdeModule()));
	}
	
}
